name: ci/cd pipeline

on: [push]

jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./01-svelte_kit-js/frontend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn install
      - name: Build frontend
        run: yarn build

  build-cms:
    name: build-cms
    runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./01-svelte_kit-js/cms

      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: "16.x"
        - name: Install dependencies
          run: yarn install
        - name: Build frontend
          run: yarn build
